Origin
sazverev/sprint-1 pull request #1
Opened 2021-05-16 19:46 UTC by sazverev

created the layout
add file logo_header.svg
rename file logo.svg - logo_footer.svg
:)

2021-05-17 12:01 UTC, bautrukevich requested changes
В целом всё очень круто! Ты красавчик!

В основном, есть замечания по БЭМ (над этим будем работать и более подробно разбирать, посвятим этому и следующий целый спринт).

Кроме тех замечаний, что я указал есть замечания по несоответствии макету. Может быть просто ты не нашел как включить просмотр комментариев в Фигме? Там есть немного описания того, как должны себя вести блоки.

Но всё равно есть моменты, которые нужно исправить в соответствии с макетом.

Секция `header`:
1. Высота `header` должна меняться от 600px до 768px (это есть в комментариях к макету).
2.  Текстовое содержимое `header` должно быть выровнено по центру (необходимо будет обнулить отступы у `h1` и `p`.
3. У текстового содержимого должен быть отступ слева в процентах (есть в комментариях к макету).
4. Большой круг, воздушный шар и кружок со стрелочкой (отличается положение) в `header` стоят немного по-другому.

Секция `facts`:
1. Необходимо обнулить отступы у заголовка и подзаголовка, а затем задать параметры такие, как в макете.
2. У карточек необходимо обнулить отступы у заголовка и текста, а затем задать параметры для них такие, как в макете (здесь упущен момент с высотой строки)
3. Содержимое блока с карточками сделать фиксированным по ширине. Сделать так, чтобы помещались 4 карточки в ряду на разрешении 1200 по ширине.

Секция `ataturk`:
1. Обнулить отступы для заголовка и подзаголовка. Задать отступы для них и высоту строки как в макете.
2. Высота секции отличается от той, что в макете на разрешении 1200px. Это не критично, тут непростая ситуация и мы разберем её, как можно было решить, если не получится исправить.

Секция про топ-10 мест:
1. Содержимое нужно выровнять по центру.

Секция `footer`:
1. Высота строки у текста отличается от той, что в макете (текст под логотипом и у ссылок другие отступы).
2. Размер шрифта в копирайте.
3. Разделительная полоса с прозрачностью.

Давай, дерзай!

2021-05-17 12:05 UTC, bautrukevich commented
Можно лучше:
- Название ветки `origin` не совсем отражает суть. Можно назвать было например, `feat/index-page` как я писал в теории.
- Добавить описание в README.md

2021-05-19 07:41 UTC, closed without merging

2021-05-19 19:56 UTC, sazverev commented on index.html
> +            <img src="images/logo_header.svg" alt="Логотип">
Почему так лучше?

2021-05-19 19:57 UTC, sazverev commented on index.html
>      <meta name="description" content="Page description">
Поменял. Вот сколько не делал сайты, нормально описание составить не получается

2021-05-19 19:57 UTC, sazverev commented on index.html
>          <div class="bg_circle_left"></div>
Исправил

2021-05-19 19:58 UTC, sazverev commented on index.html
>          <div class="bg_circle_right"></div>
Важно ли устанавливать такие блоки вначале или конце блока ? Я установил вначале

2021-05-19 19:58 UTC, sazverev commented on index.html
> +        <div class="logo">
Убрал

2021-05-19 20:08 UTC, sazverev commented on index.html
> +            <img src="images/balloon.png" alt="Воздушный шар">
Почему лучше?

2021-05-19 20:12 UTC, sazverev commented on index.html
> +            <h1>Удивительная Турция</h1>
<div class="header__content">
          <h1 class="title">Удивительная Турция</h1>
          <p class="description">Туристы со всего мира едут в эту сказочную страну не только за пляжным отдыхом, но и для того, чтобы поближе познакомиться с культурой и историей древних цивилизаций, ранее населявших эту землю</p>
        </div>

2021-05-19 21:10 UTC, sazverev commented on index.html
Почему это важно?

2021-05-19 22:27 UTC, sazverev commented on index.html
> +          <div class="bg_square_kaufman"></div>
Переименовал в square

2021-05-20 15:01 UTC, sazverev commented on styles/styles.css
>  }
Какая?